#!/usr/bin/env python3
"""Fit smooth phase-dependent symmetric W/D/L curves, separately per depth.
Requires numpy/scipy. Validation games are never used to estimate parameters.
"""
import json, pathlib, hashlib
import numpy as np
from scipy.optimize import minimize
from scipy.special import expit
ROOT=pathlib.Path(__file__).resolve().parents[1]
data=json.loads((ROOT/'calibration/scored-positions.json').read_text())
models=[]; reports=[]
def probs(theta,score,empty):
    phase=(60-empty)/60
    x=np.column_stack([np.ones(len(score)),phase,phase*phase])
    a=np.exp(np.clip(x@theta[:3],-12,12))
    b=np.exp(np.clip(x@theta[3:],-12,12))
    win=expit((score-a)/b); loss=expit((-score-a)/b)
    return np.column_stack([loss,np.maximum(0,1-win-loss),win])
for level in range(1,7):
    rows=[]
    for p in data['records']:
        r=p['results'][level-1]
        if not r['solved']:
            rows.append((r['score'],p['empty'],p['outcome']+1,p['split']=='train'))
    rows=np.array(rows); train=rows[:,3].astype(bool)
    def objective(theta):
        p=probs(theta,rows[train,0],rows[train,1])
        # Weak curvature regularization keeps sparse phase ends from exploding.
        return -np.log(np.maximum(1e-12,p[np.arange(len(p)),rows[train,2].astype(int)])).mean()+0.001*(theta[1]**2+theta[2]**2+theta[4]**2+theta[5]**2)
    fits=[minimize(objective,np.array([a,0,0,b,0,0]),method='L-BFGS-B',bounds=[(-8,10),(-8,8),(-8,8),(0,10),(-8,8),(-8,8)]) for a,b in [(2,5),(3,6),(0,4)]]
    fit=min(fits,key=lambda f:f.fun)
    if not fit.success: raise RuntimeError(fit.message)
    theta=fit.x; models.append(dict(level=level,a=theta[:3].tolist(),b=theta[3:].tolist()))
    def metrics(mask):
        p=probs(theta,rows[mask,0],rows[mask,1]); y=rows[mask,2].astype(int)
        target=np.eye(3)[y]; index=p[:,2]-p[:,0]; actual=y-1
        bins=[]
        for lo,hi in zip(np.linspace(-1,1,9)[:-1],np.linspace(-1,1,9)[1:]):
            m=(index>=lo)&(index<(hi if hi<1 else 1.00001))
            if m.any(): bins.append(dict(lower=float(lo),upper=float(hi),n=int(m.sum()),predicted=float(index[m].mean()),observed=float(actual[m].mean())))
        return dict(n=len(y),logLoss=float(-np.log(np.maximum(1e-12,p[np.arange(len(y)),y])).mean()),brier=float(((p-target)**2).sum(axis=1).mean()),indexMAE=float(abs(index-actual).mean()),bins=bins)
    prior=np.bincount(rows[train,2].astype(int),minlength=3)/train.sum(); baseline=-np.log(np.maximum(1e-12,prior[rows[~train,2].astype(int)])).mean()
    reports.append(dict(level=level,train=metrics(train),validation=metrics(~train),baselineLogLoss=float(baseline)))
engine_hash=hashlib.sha256((ROOT/'site/js/engine.js').read_bytes()).hexdigest()
model=dict(version=1,reference=data['reference'],seed=data['seed'],engineSha256=engine_hash,models=models)
(ROOT/'site/js/calibration-model.js').write_text('// Generated by scripts/fit-calibration.py; do not hand-tune.\nexport const CALIBRATION = '+json.dumps(model,separators=(',',':'))+';\n')
report=dict(reference=data['reference'],engineSha256=engine_hash,positions=len(data['records']),trainingGames=len(set(p['game'] for p in data['records'] if p['split']=='train')),validationGames=len(set(p['game'] for p in data['records'] if p['split']=='validation')),scoredSha256=hashlib.sha256((ROOT/'calibration/scored-positions.json').read_bytes()).hexdigest(),depths=reports)
(ROOT/'calibration/validation.json').write_text(json.dumps(report,indent=2)+'\n')
for r in reports: print(f"level {r['level']}: train {r['train']['n']}, held-out {r['validation']['n']}, log loss {r['validation']['logLoss']:.3f} vs baseline {r['baselineLogLoss']:.3f}, Brier {r['validation']['brier']:.3f}")
